<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>

  <script>
            function compareData()
{
var name = document.myform1.namee.value;
var users = document.myform1.user.value;
var mobile = document.myform1.mobilen.value;

   
   if (name=="" || users=="" || mobile=="")
  {
  alert("All  fields are required");
  return false;
   if ( myform1.ListBox2.value == -1 ) 
      alert ( "Select service." );
  return false;
  }




if(isNaN(mobile))
{
alert("Enter the valid Mobile Number");
//document.myform1.mobile.focus();
return false;
}
if((mobile.length < 10) || (mobile.length > 10))
{
alert("Mobile no. should consists of 10 digits ");
//document.myform1.mobile.select();
return false;
}
 if (mobile.charAt(0)=="0")
           {
                alert("Mobile no. should not start with 0 ");
                return false
           }
           
 var atpos=users.indexOf("@");
var dotpos=users.lastIndexOf(".");
if (atpos<1 || dotpos<atpos+2 || dotpos+2>=users.length)
  {
  alert("E-mail adress is not valid");
  return false;
  }
         
re = /^[A-Za-z\s]+$/;
if(re.test(name))
{
return true;
}
else
{
alert('Invalid Name.');
return false;

}




return true;


}
</script>
<form name="myform1" id="myform1" align="left" valign="top" Method="post" onsubmit="return compareData();" action="<?=$this->url(array('controller'=>'ivr1','action'=>'createnewu'))?>">
        
         
        <div class="clear"></div>
        <div style="width: 780px; padding: 20px">
         
            <div style="width: 700px; padding-top: 10px">
            <div style="width:130px; float: left; font-size: 12px; font-weight: bold">Name</div>
            <div style="width:230px; float: left "><input type=text  name="namee"  size="15" ></input></div></div>
            <div class="clear"></div>
            <div style="width: 700px; padding-top: 10px">
            <div style="width:130px; float: left; font-size: 12px; font-weight: bold">User ID</div>
              <div style="width:230px; float: left "><input type="text" name="user"  size="15" ></input></div>
            </div>
          <div class="clear"></div>
          
          <div style="width: 700px; padding-top: 10px">
            <div style="width:130px; float: left; font-size: 12px; font-weight: bold">Mobile No.</div>
              <div style="width:230px; float: left "><input type="text" name="mobilen"   size="15" ></input></div>
            </div>
            <div class="clear"></div>
            
            <div style="width: 700px; padding-top: 30px; float: left "> 
                    <div style="width: 130px; float: left; font-size: 12px; font-weight: bold">Select Service</div>
             <div style="width: 500px; float: left ">
            <select name="ListBox2[]" size="4" multiple="multiple"
id="ListBox2">
         <?php
   
   // print_r($resp);
   // print_r (explode(",",$this->response));
   $option=explode("#-*",$this->response);
    $option2=explode(",",$option[1]);
    
    foreach($option2 as $v1){
         if($v1!=""){?>
   <option value=<?php echo str_replace(" ","#",$v1)?>><?php echo $v1?></option><?}}?>
  </select></div></div>
  
  <div class="clear"></div>
            
                    <div style="width: 700px; padding: 30px 0 10px 130px; float: left; "> 
             <div style="width: 200px;" ><input class="submit" type="submit" id="b1" name="submit" value="Continue" onclick="return compareData();"></input>
             </div>   </div>
          </div>
        <div class="clear"></div>
</form>
