<form name="myform1" id="myform1" align="left" valign="top" Method="post" onsubmit="return compareText();" action="<?=$this->url(array('controller'=>'ivr1','action'=>'forgotpass'))?>" >
        
     <script language="javascript" type="text/javascript">
function compareData()
{
var id = document.myform1.id.value;


   
   if (id=="")
  {
  alert("Enter username ");
  return false;
  }
  return true;
}
</script>     
    
    <div style="text-align: center; font-size: 18px; padding-top: 10px; font-weight: bold">FORGOT PASSWORD</div>
        <div class="clear"></div>
        <div style="width: 780px; padding: 20px">
          <?php // print_r($this->output);?>
             <div class="clear"></div>
            <div style="width: 700px; padding-top: 10px">
            <div style="width:130px; float: left; font-size: 12px; font-weight: bold">Enter your email id</div>
            <div style="width:230px; float: left "><input type="text"  name="id"  size="15" ></input></div></div>
             <div class="clear"></div>
            
                    <div style="width: 700px; padding: 30px 0 0 130px; float: left; "> 
             <div style="width: 200px;" ><input type="submit" id="b1" name="submit" value="Submit" onclick="return compareData();"></input>
             </div>   </div>