<!--<div align="center">
    <h2>MSISDN WISE REPORT</h2> <br></br>
</div>-->
<?php //print_r($this->layout());
        //echo $this->headLink()->appendStylesheet(MEDIA_PATH.'/css/jquery.ui.css') ?>
<script>
	$(function() {
		$( "#startdatepicker" ).datepicker();
                $( "#enddatepicker" ).datepicker();
	});
	</script>
        <?php
       // print_r (explode(",",$this->response));
      //  print_r ($_REQUEST);
        ?>
 <html>
     
          <script language="javascript" type="text/javascript">
function compareDate()
{
var start = document.myform1.startdate.value;
var end = document.myform1.enddate.value;

   var startDate = Date.parse(start);
   var endDate = Date.parse(end);
   if (start=="" || end=="")
  {
  alert("Start date and End date is required");
  return false;
  }


// alert(a1);
// alert(a1.length);

 var difference = (endDate - startDate)/(86400000 * 7);
   if (difference < 0) {
       alert("The start date must come before the end date.");
       return false;
   

}
return true;
}
</script>
     
        
      
<body><form name="myform1" id="myform1" align="left" valign="top" Method="post">
        
       
        <div class="clear"></div>
        <div style="width: 780px; padding: 20px">
            
            </div>
            <div style="width: 700px; padding-top: 10px">
            <div style="width:130px; float: left; font-size: 12px; ">Start Date</div>
            <div style="width:230px; float: left "><input type=text id="startdatepicker" name="startdate" readonly="readonly" size="15" value="<?php $startdate = isset($_POST['startdate']) ? $_POST['startdate'] : null;echo $startdate;?>" ></input></div>
            <div style="width:100px; float: left; font-size: 12px; padding-left: 20px "> End Date</div>
            <div style="width:210px; float: left "><input type="text" name="enddate" id="enddatepicker" readonly="readonly" size="15" value="<?php $enddate = isset($_POST['enddate']) ? $_POST['enddate'] : null;echo $enddate;?>" ></input></div>
            </div>
             <div style="width: 700px; padding-top: 30px; float: left "> <div style="width: 130px; float: left; font-size: 14px; font-weight: bold">Select Service</div>
             <div style="width: 500px; float: left ">
                 
                   <?php if (  $_SESSION['notselected']=='not') {?>
              <select name="ListBox1[]" size="4" multiple="multiple" style="width: 180px"
                  id="ListBox1" >
        <?php
   
   // print_r($resp);
   // print_r (explode(",",$this->response));
    $option=explode("#-*",$this->response);
    $option1=explode(",",$option[1]);
   // print_r($option1);
    foreach($option1 as $v){echo $v;
    if($v!=""){?>
        <option value=<?php echo str_replace(" ","#",$v)?>><?php echo $v?></option><?}}?>
     </select>  <?}?>
                 <?php  
                     if (  $_SESSION['notselected']!='not') {?>
                    <select name="ListBox1[]" size="4" multiple="multiple" style="width: 180px">
                     <?php foreach($_POST['ListBox1'] as $one){?>
        <option value=<?php echo $one?>><?php echo $one?></option>
        <?}?>
     </select> <?}?>
             </div>
             </div>
                 
                     <div class="clear"></div>
                    <div style="width: 700px; padding-top: 30px; float: left "> <div style="width: 130px; float: left; font-size: 14px; font-weight: bold">Select Circle</div>
             <div style="width: 500px; float: left ">
          <?php if (  $_SESSION['notselected']=='not') {?>
              <select name="ListBox2[]" size="4" multiple="multiple" style="width: 180px"
                  id="ListBox2" >
        <?php
   
   // print_r($resp);
   // print_r (explode(",",$this->response));
    $option=explode("#-*",$this->response);
    $option2=explode(",",$option[0]);
    foreach($option2 as $v1){echo $v1;
    if($v1!=""){?>
        <option value=<?php echo str_replace(" ","#",$v1)?>><?php echo $v1?></option><?}}?>
     </select>  <?}?>
                 <?php  
                     if (  $_SESSION['notselected']!='not') {?>
                    <select name="ListBox2[]" size="4" multiple="multiple" style="width: 180px">
                     <?php foreach($_POST['ListBox2'] as $one){?>
        <option value=<?php echo $one?>><?php echo $one?></option>
        <?}?>
     </select> <?}?></div>
                      
                        
                         <div class="clear"></div>
                    <div style="width: 700px; padding-top: 30px; float: left "> <div style="width: 130px; float: left; font-size: 14px; font-weight: bold">Select Shortcode</div>
             <div style="width: 500px; float: left ">
       <?php if (  $_SESSION['notselected']=='not') {?>
              <select name="ListBox3[]" size="4" multiple="multiple" style="width: 180px"
                  id="ListBox3" >
        <?php
   
   // print_r($resp);
   // print_r (explode(",",$this->response));
    $option=explode("#-*",$this->response);
   $option3=explode(",",$option[2]);
   
    foreach($option3 as $v2){echo $v2;
    if($v2!=""){?>
        <option value=<?php echo str_replace(" ","#",$v2)?>><?php echo $v2?></option><?}}?>
     </select>  <?}?>
                 <?php  
                     if (  $_SESSION['notselected']!='not') {?>
                    <select name="ListBox3[]" size="4" multiple="multiple" style="width: 180px">
                     <?php foreach($_POST['ListBox3'] as $one){?>
        <option value=<?php echo $one?>><?php echo $one?></option>
        <?}?>
     </select> <?}?></div>
                
                        
                                   <div class="clear"></div>
                    <div style="width: 700px; padding-top: 30px; float: left "> <div style="width: 130px; float: left; font-size: 14px; font-weight: bold">Select Plan ID</div>
             <div style="width: 500px; float: left ">
          <?php if (  $_SESSION['notselected']=='not') {?>
              <select name="ListBox4[]" size="4" multiple="multiple" style="width: 180px"
                  id="ListBox4" >
        <?php
   
   // print_r($resp);
   // print_r (explode(",",$this->response));
    $option=explode("#-*",$this->response);
  $option4=explode(",",$option[3]);
    foreach($option4 as $v3){echo $v3;
    if($v3!=""){?>
        <option value=<?php echo str_replace(" ","#",$v3)?>><?php echo $v3?></option><?}}?>
     </select>  <?}?>
                 <?php  
                     if (  $_SESSION['notselected']!='not') {?>
                    <select name="ListBox4[]" size="4" multiple="multiple" style="width: 180px">
                     <?php foreach($_POST['ListBox4'] as $one){?>
        <option value=<?php echo $one?>><?php echo $one?></option>
        <?}?>
     </select> <?}?></div>
                
                        
                        <div class="clear"></div>
                    <div style="width: 700px; padding-top: 30px; float: left "> <div style="width: 130px; float: left; font-size: 14px; font-weight: bold">Output</div>
             <div style="width: 120px; float: left; font-size: 12px "><input type="radio" name="group1" value="E" id="group" checked> Excel</div>
             <div style="width: 120px; float: left; font-size: 12px "><input type="radio" name="group1" value="P" id="group" > Pdf</div>
             <div style="width: 330px; float: left; font-size: 12px "><input type="radio" name="group1" value="H" id="group" > Html</div>
             </div>
   
                      <div class="clear"></div>
                    <div style="width: 700px; padding: 30px 0; float: left "> 
             <div style="width: 200px; float: left; padding-left: 130px" ><input class="submit" type="submit" id="b1" name="submit" value="Summary Report" onclick="return compareDate();"></input></div>
             <div style="width: 350px; float: left; "><input class="submit" type="submit" id="b2" name="submit" value="Detailed Report" onclick="return compareDate();" ></input></div>
             </div>   
           <div class="clear"></div>  
                    </div>
                    </div>
                    </div>
                      <script>
                 $(document).ready(function() {  

               $("#b1").click(
               function() {
  $("#myform1").attr('action','/ivrproject/public/index.php/ivr1/shorts/startdate/enddate/ListBox1/ListBox2/ListBox3/ListBox4/group1<?php echo $this->startdate , $this->enddate ?>'); //alert($("#misform").attr('action'));
  
           
               });
              
           });
            </script>  
            
        
</form>

</body>
</html>



  <script>
                 $(document).ready(function() {  

               $("#b2").click(
               function() {
  $("#myform1").attr('action','/ivrproject/public/index.php/ivr1/shortd/startdate/enddate/ListBox1/ListBox2/ListBox3/ListBox4/group1<?php echo $this->startdate , $this->enddate ?>'); //alert($("#misform").attr('action'));
  
           
               });
              
           });
            </script>
            
          <!--  <script>
                 $(document).ready(function() {  

               $("#pack2").click(
               function() {
  $("#misform").attr('action','/gdp/public/index.php/mis/pack/startdate/enddate/comboname/<?php echo $this->startdate , $this->enddate,$this->comboname;?>');
  
  
           
               });
           });
            </script> 
 <script>
                 $(document).ready(function() {  

               $("#pack4").click(
               function() {
  $("#misform").attr('action','/gdp/public/index.php/mis/pack4/startdate/enddate/comboname/<?php echo $this->startdate , $this->enddate,$this->comboname;?>');
  
  
           
               });
           });
            </script> -->
</div>
        
        <div style="display: none;" class="demo-description">
<p>The datepicker is tied to a standard form input field.  Focus on the input (click, or use the tab key) to open an interactive calendar in a small overlay.  Choose a date, click elsewhere on the page (blur the input), or hit the Esc key to close. If a date is chosen, feedback is shown as the input's value.</p>
</div><!-- End demo-description -->
<div class="clear"></div>