<html>
<form name="myform1" id="myform1" align="left" valign="top" Method="post" >

    
   
                
                <h2> Thanks for registering. 
                     Please check your e-mail id.</h2>
                 <div style="width: 700px; padding: 30px 0 0 130px; float: left; "> 
             <div style="width: 200px;" ><INPUT  class="submit" TYPE="button" id="b1" VALUE="Back" onClick="history.go(-1);"></input>
             </div>   </div>
    <br></br>
          
                </form>
                </html>




