<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
<!--<link href="css/style.css" rel="stylesheet" type="text/css" />-->

<?php
     echo $this->headLink()->appendStylesheet(MEDIA_PATH.'/css/style1.css'); 
        ?>
</head>

<body>
<!--<div class="wrap">
<div style="height:120px; border-bottom:#666 solid 2px">
<a href="#"><div id="logo"></div></a>
<div style="float:right; width:250px; margin-top:30px">
<div>welcome XXXX </div>
<div>IVR Repoting Admin</div>
<div class="login_time">Last Login : 19/06/2011, 17:30</div>
</div>

</div>
<div class="clear"></div>
<div id="ddblueblockmenu">
<ul>
<li><a href="#">MSSIDN wise report</a></li>
<li><a href="#">Shortcode/ Plan ID wise report</a></li>
<li><a href="#">What's Revised</a></li>
<li><a href="#">Help Forums</a></li>
</ul>
</div>

<div><h3 align="center">Welcome to IVR admin</h3></div>

</div>-->
<h2 align="center">Welcome to IVR Reporting Admin</h2>
</body>
</html>
