<html> 
<body>  
<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center" link="#000000" alink="#000000" bgcolor="#ffffff" text="#000000" marginheight="0" marginwidth="0" vlink="#000000">
<table class="txt" align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody><tr> 
    <td style="padding-left:20px">
    <img src="http://119.82.69.212/kmis/services/hungamacare/images/logo.png" alt="Hungama" align="left" border="0" hspace="0" vspace="15"></td>
  </tr>
  <tr>
    <td bgcolor="#0369b3" height="1"></td>
  </tr>
</tbody></table>
<br/><br/>
<table align="center" bgcolor="#0369b3" border="0" cellpadding="1" cellspacing="1" width="40%">
    <tbody><tr> 
      <td align="center" bgcolor="#ffffff"> 
        <table class="txt2" bgcolor="#e6e6e6" border="0" cellpadding="0" cellspacing="1" width="100%">
          <tbody><tr> 
            <td colspan="2" align="center" bgcolor="#ffffff" height="25"><strong>Admin 123
              Login </strong> </td>
          </tr>
		 <form name="frm" action="<?php echo $this->url(array('controller'=>'signup','action'=>'signup'))?>" method="post"> 
          <tr> 
            <td style="padding-left: 5px;" bgcolor="#ffffff" height="35">User Name 
              : </td>
            <td style="padding-left: 5px;" bgcolor="#ffffff" height="35"> 
              <input name="login" class="in" size="25" type="text">
            </td>
          </tr>
          <tr> 
            <td style="padding-left: 5px;" bgcolor="#ffffff" height="35">Password 
              : </td>
            <td style="padding-left: 5px;" bgcolor="#ffffff" height="35"> 
              <input name="pass" class="in" size="25" type="password">
            </td>
          </tr>
          <tr align="center"> 
            <td style="padding-left: 5px;" colspan="2" bgcolor="#ffffff" height="35"> 
              <input name="submit" class="in" value="Submit" type="submit">
              &nbsp;&nbsp;&nbsp;
              <input class="in" value="Reset" type="reset">
             </td>
          </tr></form>
        </tbody></table>
      </td>
    </tr>
  </tbody></table>
</form>  
</body>  
</html>