<!DOCTYPE html>
<html lang="en">
<head>
 <title>Hungama Web - Sign In</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link href="../../assets/css/bootstrap.css" rel="stylesheet" />
<link href="../../assets/css/bootstrap-responsive.css" rel="stylesheet">
<script type="text/javascript" src="../../assets/js/jquery.js"></script>
<script language="javascript" type="text/javascript" src="http://119.82.69.212/kmis/services/hungamacare/quickstart/public/datetimepicker.js">
</script>
    </head>
<body>
    <div class="container" id="container">

 <div class="content">
<table class="txt" align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody><tr> 
    <td style="padding-left:20px">
    <img src="http://119.82.69.212/kmis/services/hungamacare/images/logo.png" alt="Hungama" align="left" border="0" hspace="0" vspace="15"></td>
   
  </tr>
</tbody></table>

<table class="table table-condensed table-bordered">
<tr> 
<td><strong><a href='<?php echo $this->url(array('controller'=>'celibrity','action'=>'index'))?>'><font size='2'>Show Celibrity Details</font></a></strong></td>
<td align="right" bgcolor="#ffffff" height="25"><strong><a href='<?php echo $this->url(array('controller'=>'celibrity','action'=>'uploadindex'))?>'><font size='2'>Upload SMS Verbiage</font></a></strong> </td> 
<td align="right" bgcolor="#ffffff" height="25"><strong><a href='<?php echo $this->url(array('controller'=>'celibrity','action'=>'pushedmsghistory'))?>'><font size='2'>Follower History</font></a></strong></td>
<td align="right" bgcolor="#ffffff" height="25"><strong><a href='<?php echo $this->url(array('controller'=>'celibrity','action'=>'showmsgstatus'))?>'><font size='2'>Show Message History</font></a></strong></td>
<td align="right" bgcolor="#ffffff" height="25"><strong><a href='<?php echo $this->url(array('controller'=>'signup','action'=>'index'))?>'><font size=4>Logout</font></a></strong></td>
</tr>
</table>
<table class="table table-condensed table-bordered">
    <tbody>
    <tr> 
	<td colspan="2" align="center" bgcolor="#ffffff" height="25"><strong>Content Details</strong> </td>
    </tr>

<tr>
<form name="frm" id='frm' action="<?php echo $this->url(array('controller'=>'signup','action'=>'showcontentmanager'))?>" method="post"> 		
<!--<td>Date&nbsp;:<input type='text' name='startdate' value="<?php echo $this->mydate ;?>">-->
		<td>
		Select Date <input id='startdate' name='startdate' type="text" size="25">
		<a href="javascript:NewCal('startdate','ddmmyyyy')"><img src="http://119.82.69.212/kmis/services/hungamacare/quickstart/public/cal.gif" width="16" height="16" border="0" alt="Pick a date"></a>
		
		&nbsp;Celebrity <select name='cName'>
		<option value=''>Select All</option>
		<?php foreach($this->response1 as $row){?>
			<option value="<?php echo $row['Celeb_Id']; ?>" <?php if(isset($this->ce_name) && $this->ce_name==$row['Celeb_Id']) echo 'selected';?>><?php echo $row['Celeb_Name'];?></option>
		<?php }?>
		</select><input type='submit' name='submit' value='Search'></td>
</form>
</tr>
</tbody>
</table>
<table class="table table-condensed table-bordered">
    <tbody>
    <tr>
		<th><font size='2'>Date</font></th>
		<th><font size='2'>Celebrity Name</font></th>
		<th><font size='2'>Celebrity Description</font></th>
		<th><font size='2'>Message Text</th><th><font size='2'>Var Date</font></th>
	</tr>
	<?php foreach($this->response as $row)
	{?>
	<tr>
		<td align='center'><font size='2'><?php echo $row['Date'];?></font></td>
		<td align='center'><font size='2'><?php echo $row['Celeb_Name'];?></font></td>
		<td align='center'><font size='2'><?php echo $row['Celeb_Description'];?></font></td>
		<td align='center'><font size='2'><?php echo $row['Msg_Text'];?></font></td>
		<td align='center'><font size='2'><?php echo $row['varDate'];?></font></td>
	</tr>
	<?php }?>
	
    </tbody>
</table>
  
</body> 
        </div>
    </div>
</html>
<?php
//echo "<pre>";print_r($this->response1);
?>
