<html> 
<head>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Auto Complete</title>


<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js"></script>
<script>
function suggest(inputString)
{
	if(inputString.length == 0) 
	{
		$('#suggestions').fadeOut();
	} 
	else
	{
		$('#country').addClass('load');
		$.post("http://119.82.69.212/kmis/services/hungamacare/quickstart/public/autosuggest.php", {queryString: ""+inputString+""}, function(data)
		{
		if(data.length >0)
		{
			$('#suggestions').fadeIn();
			$('#suggestionsList').html(data);
			$('#country').removeClass('load');
		}
		});
	}
}

function fill(thisValue) {
		$('#country').val(thisValue);
		setTimeout("$('#suggestions').fadeOut();", 600);
	}

</script>

<style>
#result {
	height:20px;
	font-size:16px;
	font-family:Arial, Helvetica, sans-serif;
	color:#333;
	padding:5px;
	margin-bottom:10px;
	background-color:#FFFF99;
}
#country{
	padding:3px;
	border:1px #CCC solid;
	font-size:17px;
}
.suggestionsBox {
	position: absolute;
	left: 280px;
	top:0px;
	margin: 26px 0px 0px 0px;
	width: 200px;
	padding:0px;
	background-color: #000;
	border-top: 3px solid #000;
	color: #fff;
}
.suggestionList {
	margin: 0px;
	padding: 0px;
}
.suggestionList ul li {
	list-style:none;
	margin: 0px;
	padding: 6px;
	border-bottom:1px dotted #666;
	cursor: pointer;
}
.suggestionList ul li:hover {
	background-color: #FC3;
	color:#000;
}
ul {
	font-family:Arial, Helvetica, sans-serif;
	font-size:11px;
	color:#FFF;
	padding:0;
	margin:0;
}

.load{
background-image:url(loader.gif);
background-position:right;
background-repeat:no-repeat;
}

#suggest {
	position:relative;
}

</style>
</head>
</head>

<body>  
<table class="txt" align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
 <tbody>
  <tr> 
    <td style="padding-left:20px">
    <img src="http://119.82.69.212/kmis/services/hungamacare/images/logo.png" alt="Hungama" align="left" border="0" hspace="0" vspace="15"></td>
  </tr>
  <tr>
    <td bgcolor="#0369b3" height="1"></td>
  </tr>
  </tbody>
 </table>

 <table align="center" border="0" cellpadding="1" cellspacing="1" width="50%">
	 <tr align='right'>
	  <td><a href='<?php echo $this->url(array('controller'=>'signup','action'=>'showcontentmanager'))?>'>Back</td>
	 </tr>
</table>

<form name='frmw' action="<?php echo $this->url(array('controller'=>'Celibrity','action'=>'searchcelebrity'))?>" method="post">
<table align="center" border="0" cellpadding="1" cellspacing="1" width="50%">
 <tbody>
    <tr bgcolor='#0369b3'> 
	<td colspan="2" align="center" bgcolor="#ffffff" height="25"><strong>Search Celibrity Details</strong> </td>
    </tr>
<tr align='center'><td>
	<div id="suggest">Select celebrity:
      <input type="text" size="25" name='srcCelebrity' value="" id="country" onkeyup="suggest(this.value);" onblur="fill();" class="" />
	  <div class="suggestionsBox" id="suggestions" style="display: none;">
	<div class="suggestionList" id="suggestionsList"> &nbsp; </div>
      </div>
   </div>
</td></tr>
<tr align='center'><td><input type='submit' name='serch' value='Find'></td></tr>
  </tbody>
</table>
</form>

</body>  
</html>
